### ISSUE TITLE
Implement synchronize merge code added by #1992

### ISSUE THREAD

**Issue by droidmonkey** [keepassxreboot/keepassxc#2339]
The code introduced by #1992 is just backend, but introduces significant use cases. It still requires plumbing to the GUI to resolve the following issues:

 - [ ] #1152 - Allow review of merge changes prior to executing merge
 - [ ] #2202 - Right-click -> merge selected entries
 - [ ] #1010 - Merging always marks database dirty
 - [ ] #2184 - Synchronize from CLI

The following are being implemented by #2109:

 - [ ] #90 - Sync changes from another file (real-time)
