### ISSUE TITLE
libkdbx tracking issue

### ISSUE THREAD

**Issue by phoerious** [keepassxreboot/keepassxc#5717]
## Summary
We are separating core KDBX functionality from the GUI parts in order to provide a standalone libkdbx, which can be used by other applications as well.

The following issues are tracking parts of this endeavour and have to be completed first:

- [ ] Allow building core functionality and CLI without QtWidgets (almost or completely? done)
    - #1714
- [ ] Move everything platform-specific to OSUtils
    - #5566
- [ ] Split OSUtils into separate dynamic libs
- [ ] Build separate libkdbx.dll/so/dylib

**Comment by AD-Thiago** [comment]
## Análise Técnica e Roadmap para Conclusão do libkdbx

Excelente progresso até agora! A separação de QtWidgets e a organização do OSUtils foram passos fundamentais. Gostaria de contribuir com uma análise detalhada dos desafios restantes e propostas concretas para completar este EPIC.

---

## **Desafios Remanescentes**

### **1. Split do OSUtils em Dynamic Libs Separadas**

O OSUtils atualmente contém código específico de plataforma (Windows, macOS, Linux/Unix). Para criar bibliotecas dinâmicas verdadeiramente isoladas, precisamos resolver:

#### **Problema: Circular Dependencies**
Se `libkeepassxc-core` depende de `libkeepassxc-osutils`, mas OSUtils precisa de tipos definidos em core, criamos dependências circulares.

**Solução Proposta: Interface/Implementation Pattern**

```cmake
# CMakeLists.txt structure
add_library(keepassxc-core SHARED
    src/core/Database.cpp
    src/core/Entry.cpp
    # ... sem dependências de OSUtils
)

add_library(keepassxc-osutils-interface INTERFACE)
target_include_directories(keepassxc-osutils-interface INTERFACE
    src/osutils/include
)

# Platform-specific libs
if(WIN32)
    add_library(keepassxc-osutils SHARED
        src/osutils/OSUtilsWin.cpp
        src/osutils/win/ScreenLockListenerWin.cpp
    )
    target_link_libraries(keepassxc-osutils
        PRIVATE keepassxc-core
        PUBLIC keepassxc-osutils-interface
    )
elseif(APPLE)
    add_library(keepassxc-osutils SHARED
        src/osutils/OSUtilsMac.mm
        src/osutils/macutils/MacUtils.mm
    )
    target_link_libraries(keepassxc-osutils
        PRIVATE keepassxc-core
        PUBLIC keepassxc-osutils-interface
        PUBLIC "-framework Foundation" "-framework AppKit"
    )
elseif(UNIX)
    add_library(keepassxc-osutils SHARED
        src/osutils/OSUtilsLinux.cpp
        src/osutils/nixutils/NixUtils.cpp
    )
    target_link_libraries(keepassxc-osutils
        PRIVATE keepassxc-core
        PUBLIC keepassxc-osutils-interface
        PUBLIC Qt${QT_VERSION_MAJOR}::DBus
    )
endif()
```

**Vantagem**: Cada plataforma tem sua própria shared lib, permitindo builds multi-plataforma mais eficientes.

---

### **2. Build Separate libkdbx.dll/so/dylib**

Este é o objetivo final e o mais complexo. Precisamos definir:

#### **a) Escopo da libkdbx**

**Proposta de Arquitetura:**

```
libkdbx (Shared Library)
├── Core Database Types
│   ├── Database
│   ├── Group
│   ├── Entry
│   ├── Metadata
│   └── Icon Cache
├── Cryptography
│   ├── SymmetricCipher (AES, ChaCha20)
│   ├── KDF (Argon2, AES-KDF)
│   └── Key Derivation
├── Format Handlers
│   ├── KdbxReader
│   ├── KdbxWriter
│   ├── KdbxXmlReader
│   └── KdbxXmlWriter
├── Utilities
│   ├── PasswordGenerator
│   ├── PasswordHealth
│   └── EntrySearcher
└── Minimal OS Abstractions
    └── FileIO interface (não implementação)
```

**Exclusões críticas da libkdbx:**
- ❌ Qualquer código Qt GUI (QWidget, QDialog, etc.)
- ❌ Integrações específicas de plataforma (Browser, SSH Agent)
- ❌ Auto-Type (depende de X11/Windows API)
- ❌ YubiKey/Hardware tokens (pode ser plugin)

#### **b) Dependências Aceitáveis**

```cmake
# libkdbx dependencies
find_package(Qt${QT_VERSION_MAJOR} REQUIRED COMPONENTS Core)
find_package(Botan REQUIRED)  # ou libgcrypt
find_package(argon2 REQUIRED)
find_package(ZLIB REQUIRED)

add_library(kdbx SHARED
    src/format/KdbxReader.cpp
    src/format/KdbxWriter.cpp
    src/format/KdbxXmlReader.cpp
    src/format/KeePass2.cpp
    src/crypto/SymmetricCipher.cpp
    src/crypto/kdf/Argon2Kdf.cpp
    src/core/Database.cpp
    src/core/Group.cpp
    src/core/Entry.cpp
    # ...
)

target_link_libraries(kdbx
    PUBLIC Qt${QT_VERSION_MAJOR}::Core  # QString, QByteArray, QIODevice
    PRIVATE Botan::Botan
    PRIVATE argon2
    PRIVATE ZLIB::ZLIB
)

set_target_properties(kdbx PROPERTIES
    VERSION ${PROJECT_VERSION}
    SOVERSION ${PROJECT_VERSION_MAJOR}
    PUBLIC_HEADER "include/kdbx/Database.h;include/kdbx/Entry.h;..."
)

install(TARGETS kdbx
    LIBRARY DESTINATION lib
    PUBLIC_HEADER DESTINATION include/kdbx
)
```

#### **c) API Stability & Versioning**

**Problema**: A API do KeePassXC atual é muito acoplada. Precisamos definir uma API pública estável.

**Solução: Visibility Attributes**

```cpp
// include/kdbx/kdbx_export.h
#if defined(_WIN32) || defined(__CYGWIN__)
    #ifdef KDBX_BUILDING_LIB
        #define KDBX_EXPORT __declspec(dllexport)
    #else
        #define KDBX_EXPORT __declspec(dllimport)
    #endif
#else
    #define KDBX_EXPORT __attribute__((visibility("default")))
#endif

// src/core/Database.h
class KDBX_EXPORT Database {
public:
    bool open(const QString& password, QIODevice* device);
    bool save(QIODevice* device);
    Group* rootGroup() const;
    // ... API pública
    
private:
    class Private; // PIMPL para ocultar detalhes de implementação
    std::unique_ptr<Private> d;
};
```

**CMake configuration:**

```cmake
set_target_properties(kdbx PROPERTIES
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN YES
)

target_compile_definitions(kdbx PRIVATE KDBX_BUILDING_LIB)
```

---

## **Roadmap de Implementação Sugerido**

### **Fase 1: Refatoração Interna (2-3 meses)**

1. **Criar namespace isolado**: `namespace KDBX { ... }`
2. **Extrair dependências Qt GUI**: 
   - Substituir `QMessageBox::critical()` por callbacks ou exceptions
   - Remover `QApplication::clipboard()` do core
3. **PIMPL Pattern**: Aplicar em todas as classes públicas da API
4. **Definir API pública clara**: Headers em `include/kdbx/`

### **Fase 2: Build System (1-2 meses)**

1. **Criar estrutura CMake modular**:
```
src/
├── libkdbx/
│   ├── CMakeLists.txt
│   ├── core/
│   ├── format/
│   └── crypto/
├── osutils/
│   ├── CMakeLists.txt
│   ├── win/
│   ├── mac/
│   └── unix/
└── gui/
    └── CMakeLists.txt
```

2. **Configurar symbol visibility**
3. **Adicionar testes de linkagem**: Garantir que libkdbx não depende de GUI

### **Fase 3: Integração & Testes (2-3 meses)**

1. **Criar exemplo standalone**:
```cpp
// examples/kdbx_reader.cpp
#include <kdbx/Database.h>
#include <kdbx/Entry.h>
#include <QFile>

int main() {
    KDBX::Database db;
    QFile file("test.kdbx");
    file.open(QIODevice::ReadOnly);
    
    if (db.open("password", &file)) {
        for (auto* entry : db.rootGroup()->entries()) {
            qDebug() << entry->title();
        }
    }
    return 0;
}
```

2. **CI/CD**: Build separado da libkdbx em matriz de plataformas
3. **Testes de ABI**: Usar `abidiff` para detectar quebras

---

## **Desafios Específicos de Plataforma**

### **Windows**

- **DLL Hell**: Garantir que Qt DLLs sejam encontradas
- **MSVC vs MinGW**: Testar ambos compiladores
- **Solution**: Usar CMake INSTALL(TARGETS) com RUNTIME DESTINATION

### **macOS**

- **Framework Bundle**: Considerar criar `KDBX.framework`
```cmake
set_target_properties(kdbx PROPERTIES
    FRAMEWORK TRUE
    FRAMEWORK_VERSION A
    MACOSX_FRAMEWORK_IDENTIFIER org.keepassxc.kdbx
    MACOSX_FRAMEWORK_BUNDLE_VERSION ${PROJECT_VERSION}
)
```

### **Linux**

- **RPATH**: Configurar corretamente para encontrar libs
```cmake
set_target_properties(kdbx PROPERTIES
    BUILD_RPATH_USE_ORIGIN TRUE
    INSTALL_RPATH "$ORIGIN/../lib"
)
```

---

## **Considerações de Segurança**

1. **Memory Wiping**: Garantir que libkdbx limpa memória sensível (relacionado a #7335)
2. **Thread Safety**: Documentar se Database é thread-safe
3. **Exception Safety**: Garantir que exceções não vazam dados

---

## **Benefícios da Conclusão**

✅ **Reutilização**: Outros projetos podem usar libkdbx (KeePassDX, KeePassium ports)  
✅ **Testing**: Testes unitários mais rápidos (sem GUI)  
✅ **Mobile**: Base sólida para apps iOS/Android  
✅ **Maintainability**: Separação clara de responsabilidades  

---

## **Próximos Passos Concretos**

1. **Criar branch `feature/libkdbx-separation`**
2. **Definir API pública** em `docs/libkdbx-api.md`
3. **Refatorar Database.h/cpp** para aplicar PIMPL
4. **Criar CMakeLists.txt modular** em `src/libkdbx/`
5. **PR incremental**: Não tentar fazer tudo de uma vez

Estou disponível para contribuir com PRs específicos para qualquer uma dessas etapas, caso haja interesse da equipe de mantenedores.
