### ISSUE TITLE
Semi-automatic password renewal

### ISSUE THREAD

**Issue by michaelk83** [keepassxreboot/keepassxc#6500]
## Summary
Automate the password renewal process, along the following lines:
1. For each generated password, remember the password generator settings that were used to generate it. If a preset was used, just remembering the preset name is enough (and may be preferable).
1. Save the password renewal form URL along with the password.
1. Allow separate auto-type settings for the password renewal form. By default this is: type old password &rarr; (tab) &rarr; type new password &rarr; (tab) &rarr; type new password again.
1. The first time a password is used after its expiry date, after auto-typing the old password, ~~automatically~~ load the renewal form.
1. Generate a new password using the saved generator settings, and auto-type it into the renewal form. The previous password should be saved to the entry history and taken from there (this is necessary in case the renewal fails on the 1st attempt).
1. For first-time setup, after the user gets redirected to the renew page by the service, or loads it manually, they can copy the URL into the Renewal URL field, adjust the auto-type settings if necessary (usually the default should work), and initiate the renewal process as usual.
1. A separate `Renew` button can update the password only in KPXC, without auto-typing the password renewal form (#6323).

## Context
Inspired by #6451. This would make password renewal easier, and encourage users to set expiry dates on more passwords (with this enabled, KPXC can have all auto-generated passwords expire by default with a global default setting such as 6 months). Related to #2010.

## Suggested Wokflow
1. User loads the renewal URL (or non-web application form).
1. User focuses the first relevant field, and initiates the renewal auto-type sequence (special shortcut, browser-extension sub-menu, or via the auto-type selection dialog). A default renewal sequence will be provided by KPXC to minimize manual configuration.
1. The `{NEWPASSWORD}` auto-type action takes care of the renewal process on KPXC's end, as detailed in #6520 (prompts for a new password, saves it, etc).
1. The fields are filled by the renewal auto-type sequence.
1. User clicks Submit to update the host website or application (or use the `{ENTER}` auto-type action).

**Dealing with picky websites** (#6323):

6. If the password is rejected by a picky website, undo the password change in KPXC (restore from entry history), update the password generator settings, and try again.
1. In a more advanced implementation, the new password isn't saved until the user confirms that the host website or application accepted it (see enhancements below).

## Implementation Details
This can be broken down into the following steps (each in its own PR, more or less).

**MVP:**
- [ ] Infrastructure: Auto-update password expiry dates: #2010
- [ ] Manual renewal form (without auto-type): #6323

**Auto-filling the renewal form:** (saves on having to copy-paste each password field individually)

- [ ] Main logic: Auto-type `{NEWPASSWORD}` action (#6520).
- [ ] Auto-fill MVP: If the password field is a reference, `{NEWPASSWORD}` should dereference to update the original entry (last point of #6520). This allows renewal auto-type to be handled via reference entries as a temporary solution until the following extras are added.
- [ ] Add per-entry renewal settings, allowing the renewal URL and auto-type sequence to be specified. We can avoid triggering this sequence automatically if that makes things easier or more reliable. To avoid unnecessary manual configuration, these should default as follows: 
    - [ ] Default URL from https://github.com/apple/password-manager-resources/blob/main/quirks/change-password-URLs.json (sanity check against the entry's main URL: should have the same domain).
    - [ ] Default renewal sequence: `{PASSWORD}{TAB}{NEWPASSWORD}{TAB}{NEWPASSWORD}`
    - [ ] Default matching rules: the renewal URL must match (prevent phishing for web passwords).
- [ ] List the renewal sequence in the auto-type selection dialog, maybe filtered by Login / Renewal options.

**Enhancements:**
- [ ] In the browser extension, add a submenu to initiate specifically either the login or renewal auto-type sequence.
- [ ] When an expired password is used (e.g. copied), prompt the user to renew the password. If OK'ed, load the relevant forms.
- [ ] Load the relevant forms from the DB reports (#6032).
- [ ] `Undo Password Change` button to restore the previous password if the new one is rejected by a picky website (complements #6323).
- [ ] When running a renewal auto-type sequence, optionally defer saving the new password until the sequence is complete, and then prompt the user whether to save or discard (complements #6323 in the auto-type context).
- [ ] Go To icon next to each URL field to load that URL in a browser (if not already implemented).
- [ ] In the password generator, remember the last settings for each generated password. Load them automatically when that password is being edited or renewed. If it's an unmodified preset, just remember the preset name (#2628).
- [ ] Setting to skip the new password prompt for generated passwords (regenerate automatically using the saved password generator settings).
- [ ] Similar handling for the password reset (forgot password) special case.

**Comment by michaelk83** [comment]
From a [comment on #6451](https://github.com/keepassxreboot/keepassxc/issues/6451#issuecomment-834659488):
> I see some difficulties with the implementation though: changing the password on many sites is not as simple as just having three text fields (old + new + new confirm). Sometimes you need to reauthenticate, sometimes it's a password reset link sent out by email.

I've assumed reauthentication is the most common mode. The renewal form is loaded after logging in. The login form can already be auto-typed with the current feature-set. See point 4 of the OP.

Password reset is a separate case. You may have to load the the reset URL manually, but if it can be matched (e.g. using a wildcard for the authentication token), the rest can still be automated in a similar manner. You would just need a different URL and a different auto-type sequence. Otherwise, at least the password re-generation step can still be automated, and the password step entry can be at least partially automated (copy-paste, at a minimum).

> Not to mention all the passwords which aren't for web applications but for other uses. How would the auto-renewal work in that case?

I think auto-type works not only for browser windows, as long as it can match the window title? So the principle is similar, just not URL-based.

All in all, this feature is just the existing password generator + the existing auto-type feature + some extra settings and logic to use them for password renewal.

**Comment by michaelk83** [comment]
I'm not a security expert, and you may be right. But the way I understand it:

For regular password renewal, you need to log in first. The renewal can't proceed without at least access to the current login credentials. If the login credentials are compromised, whoever got access to them can already log in and change the password anyway. So one can similarly claim that automating the login is potentially dangerous (yet it is automated).

For the automated renewal, we also need to update the DB, so it can only occur when the DB is unlocked. If your DB is compromised, the attacker can already reset every account in there, even without automation. So *I think* it doesn't increase the risk.

For password reset, the reset link is sent to your email, so there's an extra layer of protection there, as long as your email isn't compromised as well. If it is compromised, then again, the attacker can already reset your passwords anyway, even without automation.

Similarly, for regular renewal, we can still keep the user in the loop at whatever steps that are deemed most risky to automate (though I'm not sure which ones those are). It doesn't have to be 100% automatic. It just needs to remind the user when they use an expired password, and then save the bunch of clicks and typing that would be needed to renew it manually.

Indeed, the renewal operation would be triggered by user action: either the user logging in with an expired password (copying or auto-typing it), or them manually loading the renewal page (which is then matched by the renewal auto-type rules), or even manually pressing the Renew button (point 6 of the OP).

If you can come up with specific scenarios where the DB is *not* compromised, but this automation can still be exploited to steal secrets, we can discuss those in more detail. But as a non-expert, I can't think of any at the moment.

**Comment by michaelk83** [comment]
To put it shortly: if you can log in, you can change the password, and we already automate login. For the purpose of this feature, a password renewal form can be viewed as a special type of login form.

**Comment by michaelk83** [comment]
The discussion in #6519 is also relevant to this issue. Password renewal URLs may be more stable than login URLs, but they can still change from time to time. There are a couple issues here:

1. Matching the correct URL, and distinguishing between password renewal, password reset (forgot password), and regular login. For each case, we'll need to pick the correct auto-type sequence, otherwise the user will have to pick manually. This can make each of these more error prone. If the user has to make a selection for each login, that's also less convenient.
1. Loading the correct URL during renewal. If the URL has changed, this step will fail, and renewal can't proceed. For password reset (which sends a temporary link to the user's email), loading the URL will have to be manual anyway, and it may need to be manual for regular password renewal (but this may benefit security?).

I'm thinking the following approach:

1. User should load the URLs manually. We can add a "Go To" icon next to the URL fields to semi-automate this.
1. Auto-type settings should preferentially be linked to specific URL fields where possible (this doesn't work for non-web application passwords, for example).
1. Can we check the field count against the auto-type sequence (this would also help with cases like #6508)? The browser plugin should manage that for web passwords. For non-web, this could be difficult (if not impossible).
1. Pick the auto-type sequence that matches best based on all of these criteria (window title also). If we present a selection dialog, then maybe bold the best match.
1. In the browser plugin, if there's an auto-type button, it can have a sub-menu to manually select between the login, renewal, and reset sequence types. The auto-type selection window could have a similar filter.
1. The auto-type sequence should trigger password regeneration, instead of the other way. A `{NEW-PASSWORD}`  action in the sequence. Subsequent `{PASSWORD}` actions should then use the previous password.

I will update the OP with this in mind.

**Comment by droidmonkey** [comment]
This is basically a duplicate of #6323 and #6032

**Comment by michaelk83** [comment]
@droidmonkey I'm updating the OP. Also just noticed #5399 from one of your links. I'll go over those other issues and will update.

But yes, current idea is somewhat like a semi-automated walkthrough.

**Comment by michaelk83** [comment]
Updated. See particularly the new Suggested Workflow and Implementation Details sections.

@droidmonkey #6032 mainly deals with opening the forms on both ends (browser and KPXC). It doesn't deal with the actual renewal process, nor with reminding the user to renew when they use an expired password. #6323 is primarily concerened with picky websites, and doesn't deal with password entry in the renewal form. Picky websites can be handled with appropriate password generator settings and an Undo button (password history). This issue is wider and more detailed.

Btw, this should probably be marked Epic, since there are several sub-issues? And also UX, I guess.

**Comment by droidmonkey** [comment]
Yah I'm wary of all the issues around this feature. It complicates our discussion and implementation. Simple simple simple. Should be going through your mind at ALL times.

**Comment by michaelk83** [comment]
We can deal with each sub-issue and bullet point one at a time. This isn't from today to tomorrow. Thanks for reopening #6520.

**Comment by JohnLGalt** [comment]
One major problem that I actually didn't think about before is that by introducing automation of this type you're setting up your users to make them more complacent to fall for phishing attacks via email.  And I wouldn't have thought of it but for the fact that I was targeted with a bogus Dropbox message just yesterday that didn't get sent to spam, which said someone had tried to access my account, and took me to a very realistic (visually a 99% copy) of dropbox's own PW reset page.  In fact, the reason I caught it so easily was because KPCX wasn't providing me with a password for dropbox for the site - because, naturally, the URL was incorrect.

For power users, and those with a heightened sense of security, this could definitely be a blessing - certainly I wouldn't blame KPXC if I had fallen for that site last night.  But for the average user, the vast majority are _not_ going to see falling for this type of scam as **their _own_ fault** because they did not verify the URL - _they'll see it as KPXC's fault_ for moving forward with a false PW reset function so easily.

**Comment by michaelk83** [comment]
Assuming the renewal auto-type sequence is still subject to URL matching, it shouldn't go through on a phishing website. With a manual renewal process, you may just go ahead a copy-paste your passwords there (and submit).

**Comment by michaelk83** [comment]
Update the OP some more:
- Use #6323 as MVP.
- Separate the auto-type points to their own sub-group under Implementation Details.
- Phishing prevention when renewing web passwords.

**Comment by droidmonkey** [comment]
We are going to focus on #6323 instead as a final solution.
