### ISSUE TITLE
Auto-type: `{NEWPASSWORD}` action

### ISSUE THREAD

**Issue by michaelk83** [keepassxreboot/keepassxc#6520]
This is a sub-issue of #6500. A new `{NEWPASSWORD}` auto-type action should:

- [ ] Prompt for a new password. User can enter a manual password or launch the password generator from this prompt. This can use the same form from #6323.
- [ ] Save the new password, and remember the previous one.
- [ ] Update the password expiry date (handled by #2010).
- [ ] Subsequent `{PASSWORD}` actions in the same sequence should use the previous password.
- [ ] Subsequent `{NEWPASSWORD}` actions in the same sequence should reuse the new password without prompting.
- [ ] If the new password prompt is canceled, the sequence is aborted.
- [ ] If the **password** field is a reference, dereference to update the original entry. This allows #6500 renewal auto-fill to be handled via reference entries until it's fully implemented (can be a separate PR if this part is complicated).

(renamed from `{NEW-PASSWORD}` to `{NEWPASSWORD}` for [compatibility with KeePass 2.x](https://keepass.info/help/base/placeholders.html#newpassword))

**Comment by droidmonkey** [comment]
We rejected this already. It is not a good choice, we prefer a workflow option. I posted in your other thread.

**Comment by michaelk83** [comment]
I've read the previous discussion in #5399. This is indeed a duplicate, but I think I give better detail here.

> we prefer a workflow option (dedicated button) versus an Auto-Type sequence you have to make for each entry.

You're going to need the auto-type sequence anyway, if you want to automate all the typing for password renewal. When you have a lot of passwords that renew often, copy-pasting each password field individually can quickly become a drag.

The renewal sequence doesn't have to be trigered automatically, and as noted in #6500 and #5399, it can default to `{PASSWORD}{TAB}{NEWPASSWORD}{TAB}{NEWPASSWORD}` for most websites. So it's not something the user has to add manually for every entry, once it's implemented.

The workflow, as I see it, is:
1. User loads the renewal URL (if it's saved in the entry, there can be a Go To icon next to each URL field).
1. User focuses the first relevant field, and initiates the renewal auto-type sequence. With the browser extension, there can be a sub-menu next to the field to specifically select the renewal sequence. Otherwise it can be selected from the auto-type selection dialog.
1. The `{NEWPASSWORD}` action takes care of the update on KPXC's end (prompts for a new password, saves it, etc, as listed in the OP).
1. The fields are filled in by the auto-type sequence.
1. User clicks Submit to update the host website or application (or use the `{ENTER}` action).
1. (In a more advanced implementation, KPXC can wait for user confirmation before saving the the new password).

I think a `{NEWPASSWORD}` action as defined here is the quickest way to semi-automate password renewal, until all the other bells and wistles of #6500 are implemented (see its updated OP &rarr; Implementation Details section for the full breakdown, and Suggested Wokflow section for a more detailed workflow).

**Comment by droidmonkey** [comment]
The problem with this feature request is that you have to either make this a first class feature on the entry auto-type drop down menu (and assume tab tab) or you have to define it yourself in each entry you have. Neither is a good option. I have a much stronger preference to actually implement the New/Change Password Workflow feature #6323 instead. As such I am closing this one and focusing energy on the other one.
